
apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  labels:
    app: oficina-cardozo-api
type: Opaque
data:
  DATADOG_API_KEY: YjY4NDFiNGE5ODc1Mjk5YzI2NjBmN2E1MDhhMDYyYzU=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: datadog-config
  labels:
    app: oficina-cardozo-api
data:
  DATADOG_METRICS_URL: "https://api.datadoghq.com/api/v1/series"
  DATADOG_HOST: "oficina-cardozo-api"
