apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJVmMyNk00Y1UxUXN3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBeU1Ea3lNVFF4TlRGYUZ3MHpOakF5TURjeU1UUTJOVEZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNrTjBNWk1Wb29MTm43ZzlPOWJZYlpFN2w5UnJLZjRGczF0WWsybXV2eHdHQVJqbjZobXF3RGZ5WVMKSzE4U3FTRm5ISUo1dUp5Ti9NUzE2M2VZeTd2ZGlYdHhwM3NJYzlPRjIxSTI4WHpCcHVwMThwMExJUzFHdmVmSQpnSVl5YXQ4Ny9ma1ZMd0pCaVZUdlNPYmc2L0lJZVJGaS9VaVlZYkE0NWh6Rk1wKy91elNJRnM5bnZyWnh2VVcxClMzcGE0cnhaMDFRUzhTYnRSaU9EdTlBcEMySHQrWlIvWU5qUTl6dHJyUEhwYktydGdSY1RtUUR4enBaSWJmZlkKZm5YODdXQm8vOXhDSENCczkxQStYRlpSaVFZbEEwY2pVUDFsT21HR25pUUZ4aHBWMWo1bnRic2x0MDZKZ0l1UApjY0RUZE11a0hnU3UyVFBwdThaVC8wMVg4RTZuQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJTOEx6TWRnNW4xL2xpS2Z0TXZyZ0ZhQmd6Unh6QVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQStOTkVrRlYyUgpmL29lajE2eFBIWUtEV3c0cnBoSnF1YllIMnRuVGVHK2V3MElwRnFBeWNybkNwTHFvT29JeW83TmY2NGR1YzBGCmtQRGt5RUlQM2VoaFRrK1JRRTYrTWlaMXVzSy9sWW9Bb2hQMEMydkwvWUlRdytVdlphYkpETUR4dFZvRkZ4T08KVnRVc0x1UDNQYUJtYXZzKzBUMUlhODhvRWtqUFp4WDBEMWJFbVlwcXU2NGJabWlyYytxWHZxdGpuL0hTSzVSbgpIdGVaREp5Q3lveGNlVFI5M2Jia25wS3NpL1g3ZzVqU2R4QTZJdVhwQ2ZTaVREWE5yUjhBc3hpd3Q5MDJiN3dwClBVa2s2bmhtUFpqVUdsSnNhY20wR0k0a2x4Sk04K3RYOHJ2QUdJWXRSRGNZMXlzV3NLTVJoUFA2cWlIQWRUMDEKYmhqZ3NCd0VHa2hjCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://A0B5A376D230B3EAFABE16D12D3A94E9.sk1.sa-east-1.eks.amazonaws.com
  name: arn:aws:eks:sa-east-1:953082827427:cluster/oficina-cardozo-eks
contexts:
- context:
    cluster: arn:aws:eks:sa-east-1:953082827427:cluster/oficina-cardozo-eks
    user: arn:aws:eks:sa-east-1:953082827427:cluster/oficina-cardozo-eks
  name: arn:aws:eks:sa-east-1:953082827427:cluster/oficina-cardozo-eks
current-context: arn:aws:eks:sa-east-1:953082827427:cluster/oficina-cardozo-eks
kind: Config
preferences: {}
users:
- name: arn:aws:eks:sa-east-1:953082827427:cluster/oficina-cardozo-eks
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - sa-east-1
      - eks
      - get-token
      - --cluster-name
      - oficina-cardozo-eks
      - --output
      - json
      command: aws
